### ISSUE TITLE
Add saved info to persistency (saved in memory)

### ISSUE THREAD

**Issue by czengg** [mirai418/leaflet-ios#9]
Right now I have a variable, visited that is hard set. Should also give some value of reward name and image.

**Comment by czengg** [comment]
added functionality. Mirai can you test this with the beacons to see if the count is getting updated?

**Comment by miraiakagawa** [comment]
done (https://github.com/mirai418/leaflet-ios/commit/38a4688b1234548222e27472afe06044c017b747)
